<?php
/**
 * Copyright © CO-WELL ASIA CO.,LTD.
 * See COPYING.txt for license details.
 */
?>

<div id="casio-members-product" data-bind="scope:'casiomembers'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
       {
           "#casio-members-product": {
               "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
           }
       }
   </script>
</div>
